=begin
#Verbit Transcribe (v0.8 tech preview)

#Verbit API (application programming interface) version 1 provides programmatic access to Verbit's                     premium end-to-end transcription and captioning solution. It is based on state of the art                     ASR (automatic speech recognition) engine and thorough human review. The API can easily be                     integrated into customers' systems, enriching the user experience with transcriptions and                     closed captions for video and audio.<br><br>                     All actual schemas you can download by this link https://platform.verbit.co/api/v1/schemas/schema_name.json<br/><br/>                     <b>Testing API integration</b> can be done via sandbox token (also found on customer page) and using sandbox API url                     (https://sandbox-api.verbit.co). When using the sandbox, no real ASR or human editing is performed, and there                     are several additional params available to imitate different states of API. Please see \"Create new job\" section below.

The version of the OpenAPI document: v0.8 tech preview

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/api_error'
require 'openapi_client/models/api_error_response'
require 'openapi_client/models/api_ok_response'
require 'openapi_client/models/api_request'
require 'openapi_client/models/api_warning'
require 'openapi_client/models/auth_payload'
require 'openapi_client/models/client_error_response'
require 'openapi_client/models/client_error_response_all_of'
require 'openapi_client/models/created_order'
require 'openapi_client/models/inline_object'
require 'openapi_client/models/inline_object1'
require 'openapi_client/models/inline_response200'
require 'openapi_client/models/inline_response2001'
require 'openapi_client/models/inline_response2002'
require 'openapi_client/models/order'
require 'openapi_client/models/order_errors'
require 'openapi_client/models/output_response'
require 'openapi_client/models/rtmp_response'
require 'openapi_client/models/server_error_response'
require 'openapi_client/models/server_error_response_all_of'
require 'openapi_client/models/token'
require 'openapi_client/models/transcription_additional_info'
require 'openapi_client/models/transcription_model'
require 'openapi_client/models/transcription_output'
require 'openapi_client/models/transcription_output_delivery'
require 'openapi_client/models/transcription_output_product'
require 'openapi_client/models/transcription_output_product_live'
require 'openapi_client/models/transcription_request'
require 'openapi_client/models/transcription_rtmp_pull_input'
require 'openapi_client/models/transcription_rtmp_push_input'
require 'openapi_client/models/transcription_schedule'
require 'openapi_client/models/transcription_websocket_input'
require 'openapi_client/models/websocket_delivery'
require 'openapi_client/models/websocket_response'
require 'openapi_client/models/websocket_response_authorization'

# APIs
require 'openapi_client/api/authentication_api'
require 'openapi_client/api/order_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
